Repository envoyproxy/envoy-mobile, pull requests merged in 2019-06, with the labels that each got.

#190 build: clean up java dep structure
  library/BUILD
  library/java/io/envoyproxy/envoymobile/engine/BUILD
Labels: build, platform/android

#194 logging: add LogLevel enum to kotlin interface
  library/kotlin/io/envoyproxy/envoymobile/Envoy.kt
Labels: platform/android

#198 docs: Remove envoy bootstrap install from docs
  CONTRIBUTING.md
Labels: docs
